# Form implementation generated from reading ui file 'AgregarBodega.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BodegaDialog(object):
    def setupUi(self, BodegaDialog):
        BodegaDialog.setObjectName("BodegaDialog")
        BodegaDialog.resize(400, 300)
        self.layoutWidget = QtWidgets.QWidget(parent=BodegaDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 341, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.lineEdit_nombre = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_nombre.setText("")
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_nombre)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.lineEdit_id = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_id.setText("")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_id)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.lineEdit_limite = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_limite.setText("")
        self.lineEdit_limite.setObjectName("lineEdit_limite")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_limite)
        self.pushButton_agregar = QtWidgets.QPushButton(parent=BodegaDialog)
        self.pushButton_agregar.setGeometry(QtCore.QRect(80, 230, 75, 23))
        self.pushButton_agregar.setObjectName("pushButton_agregar")
        self.pushButton_cancelar = QtWidgets.QPushButton(parent=BodegaDialog)
        self.pushButton_cancelar.setGeometry(QtCore.QRect(230, 230, 75, 23))
        self.pushButton_cancelar.setObjectName("pushButton_cancelar")

        self.retranslateUi(BodegaDialog)
        QtCore.QMetaObject.connectSlotsByName(BodegaDialog)

    def retranslateUi(self, BodegaDialog):
        _translate = QtCore.QCoreApplication.translate
        BodegaDialog.setWindowTitle(_translate("BodegaDialog", "Dialog"))
        self.label.setText(_translate("BodegaDialog", "Nombre de Bodega:"))
        self.label_2.setText(_translate("BodegaDialog", "ID de Bodega:"))
        self.label_3.setText(_translate("BodegaDialog", "Limite de Almacen:"))
        self.pushButton_agregar.setText(_translate("BodegaDialog", "Agregar"))
        self.pushButton_cancelar.setText(_translate("BodegaDialog", "Cancelar"))
