# Form implementation generated from reading ui file 'Txt.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(377, 91)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 40, 111, 16))
        self.label.setObjectName("label")
        self.label_numero = QtWidgets.QLabel(parent=Dialog)
        self.label_numero.setGeometry(QtCore.QRect(110, 40, 47, 13))
        self.label_numero.setObjectName("label_numero")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(140, 40, 191, 16))
        self.label_3.setObjectName("label_3")
        self.label_distribuidor = QtWidgets.QLabel(parent=Dialog)
        self.label_distribuidor.setGeometry(QtCore.QRect(330, 40, 47, 13))
        self.label_distribuidor.setObjectName("label_distribuidor")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Se han agregado"))
        self.label_numero.setText(_translate("Dialog", "NULL"))
        self.label_3.setText(_translate("Dialog", "articulos con exito desde el distribuidor"))
        self.label_distribuidor.setText(_translate("Dialog", "NULL"))
