# Form implementation generated from reading ui file 'VerBodegas.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VerBodegaDialog(object):
    def setupUi(self, VerBodegaDialog):
        VerBodegaDialog.setObjectName("VerBodegaDialog")
        VerBodegaDialog.resize(641, 361)
        self.tableWidget = QtWidgets.QTableWidget(parent=VerBodegaDialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 90, 611, 231))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.pushButton_agregar = QtWidgets.QPushButton(parent=VerBodegaDialog)
        self.pushButton_agregar.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.pushButton_agregar.setObjectName("pushButton_agregar")
        self.pushButton_agregar_2 = QtWidgets.QPushButton(parent=VerBodegaDialog)
        self.pushButton_agregar_2.setGeometry(QtCore.QRect(110, 50, 75, 23))
        self.pushButton_agregar_2.setObjectName("pushButton_agregar_2")

        self.retranslateUi(VerBodegaDialog)
        QtCore.QMetaObject.connectSlotsByName(VerBodegaDialog)

    def retranslateUi(self, VerBodegaDialog):
        _translate = QtCore.QCoreApplication.translate
        VerBodegaDialog.setWindowTitle(_translate("VerBodegaDialog", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("VerBodegaDialog", "Nombre Bodega"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("VerBodegaDialog", "ID Bodega"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("VerBodegaDialog", "Capacidad"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("VerBodegaDialog", "Articulos"))
        self.pushButton_agregar.setText(_translate("VerBodegaDialog", "Imprimir"))
        self.pushButton_agregar_2.setText(_translate("VerBodegaDialog", "Eliminar"))
