# Form implementation generated from reading ui file 'AgregarArticulo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ArticuloDialog(object):
    def setupUi(self, ArticuloDialog):
        ArticuloDialog.setObjectName("ArticuloDialog")
        ArticuloDialog.resize(400, 300)
        self.layoutWidget = QtWidgets.QWidget(parent=ArticuloDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 341, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.lineEdit_nombre = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_nombre.setText("")
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_nombre)
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.lineEdit_id = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_id.setText("")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_id)
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.lineEdit_descripcion = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_descripcion.setText("")
        self.lineEdit_descripcion.setObjectName("lineEdit_descripcion")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_descripcion)
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.comboBox_distribuidor = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.comboBox_distribuidor.setObjectName("comboBox_distribuidor")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_distribuidor)
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.comboBox_bodega = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.comboBox_bodega.setObjectName("comboBox_bodega")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_bodega)
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_8)
        self.lineEdit_id_cantidad = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_id_cantidad.setText("")
        self.lineEdit_id_cantidad.setObjectName("lineEdit_id_cantidad")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_id_cantidad)
        self.pushButton_cancelar = QtWidgets.QPushButton(parent=ArticuloDialog)
        self.pushButton_cancelar.setGeometry(QtCore.QRect(230, 240, 75, 23))
        self.pushButton_cancelar.setObjectName("pushButton_cancelar")
        self.pushButton_agregar = QtWidgets.QPushButton(parent=ArticuloDialog)
        self.pushButton_agregar.setGeometry(QtCore.QRect(80, 240, 75, 23))
        self.pushButton_agregar.setObjectName("pushButton_agregar")

        self.retranslateUi(ArticuloDialog)
        QtCore.QMetaObject.connectSlotsByName(ArticuloDialog)

    def retranslateUi(self, ArticuloDialog):
        _translate = QtCore.QCoreApplication.translate
        ArticuloDialog.setWindowTitle(_translate("ArticuloDialog", "Dialog"))
        self.label_3.setText(_translate("ArticuloDialog", "Nombre del articulo:"))
        self.label_4.setText(_translate("ArticuloDialog", "ID del articulo:"))
        self.label_5.setText(_translate("ArticuloDialog", "Descripcion:"))
        self.label_6.setText(_translate("ArticuloDialog", "Nombre de distribuidor:"))
        self.label_7.setText(_translate("ArticuloDialog", "Dirigido a la bodega:"))
        self.label_8.setText(_translate("ArticuloDialog", "Cantidad a agregar:"))
        self.pushButton_cancelar.setText(_translate("ArticuloDialog", "Cancelar"))
        self.pushButton_agregar.setText(_translate("ArticuloDialog", "Agregar"))
