# Form implementation generated from reading ui file 'VerDistribuidores.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VerDistribuidorDialog(object):
    def setupUi(self, VerDistribuidorDialog):
        VerDistribuidorDialog.setObjectName("VerDistribuidorDialog")
        VerDistribuidorDialog.resize(442, 300)
        self.tableWidget = QtWidgets.QTableWidget(parent=VerDistribuidorDialog)
        self.tableWidget.setGeometry(QtCore.QRect(30, 60, 391, 231))
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(190)
        self.pushButton_agregar = QtWidgets.QPushButton(parent=VerDistribuidorDialog)
        self.pushButton_agregar.setGeometry(QtCore.QRect(40, 20, 75, 23))
        self.pushButton_agregar.setObjectName("pushButton_agregar")
        self.pushButton_agregar_2 = QtWidgets.QPushButton(parent=VerDistribuidorDialog)
        self.pushButton_agregar_2.setGeometry(QtCore.QRect(140, 20, 75, 23))
        self.pushButton_agregar_2.setObjectName("pushButton_agregar_2")

        self.retranslateUi(VerDistribuidorDialog)
        QtCore.QMetaObject.connectSlotsByName(VerDistribuidorDialog)

    def retranslateUi(self, VerDistribuidorDialog):
        _translate = QtCore.QCoreApplication.translate
        VerDistribuidorDialog.setWindowTitle(_translate("VerDistribuidorDialog", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("VerDistribuidorDialog", "Nombre Distribuidor"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("VerDistribuidorDialog", "ID Distribuidor"))
        self.pushButton_agregar.setText(_translate("VerDistribuidorDialog", "Imprimir"))
        self.pushButton_agregar_2.setText(_translate("VerDistribuidorDialog", "Eliminar"))
